name: Build Daily Image

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-and-push:
    if: github.repository_owner == 'cypht-org'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ./docker/Dockerfile
          push: true
          tags: cypht/cypht:daily
          debug: true

      - name: Log out from Docker Hub
        run: docker logout